### ISSUE TITLE
Quality and Filter Flags in bcbio-variation-recall square

### ISSUE THREAD

**Issue by tkoomar** [chapmanb/bcbio.variation.recall#15]
I am unsure what to trust when it comes to FILTER flags and the QUAL column in the final merged VCF which results from ` bcbio-variation-recall square`. 

I understand merging uses GATK's CombineVariants -- which takes the first QUAL score it sees. Am I then correct in assuming the QUAL scores in the final file are not "correct" for entire cohort? 

Additionally, how does this impact FILTER flags? Assuming I specified platypus as the caller, should I expect to see the  `PlatQualDepth`, or any other FILTER flags in the final VCF? In my particular case, a file with ~300 samples and ~24,000,000  variants had no sites with a `PlatQualDepth` filter flag, which seems  improbable -- unless they were hard filtered out. Is this the case?

**Comment by chapmanb** [comment]
Thanks for the questions. Global metrics like the QUAL and FILTER get a lot trickier when doing this type of squaring off since we don't do a global recall across all samples. In the squaring off we re-evaluate individual samples at each position, trying to use the information that there is a call in other samples to determine if the sample is no-call, reference or some alt combination there.

So in general QUAL and FILTER aren't especially useful in the squared files. We use the FILTER variants at the individual call level to determine reference versus alt so it won't appear in the global FILTER. Ideally these could be a sample level FT filter tag but that is not currently implemented.

Hope that makes sense and helps explain the implementation. Please let us know if you have other questions.

**Comment by tkoomar** [comment]
That is very illuminating, thank you for clarifying!
