### ISSUE TITLE
Reg: Joint calling with Freebayes

### ISSUE THREAD

**Issue by harish0201** [chapmanb/bcbio.variation.recall#23]
Hi!

I do have a couple of really stupid questions and I hope that I can ask here.

I have variant calls with FreeBayes for about 100 samples, with 300 more on the way. I went with FreeBayes approach because GATK GVCF generation was running pretty slow.

Anyway, I have merged the FreeBayes calls with "bcbio.variation.recall merge" and now I'm planning to square off the calls in the 100 samples.

1. Do I need to pass the individual vcfs+bams for the 100 samples as well along with the joint called vcf? Or should just use the joint called vcf with the bams?

2. Also, would it be just possible just to symlink the joint called vcf instead of refiltering the "PASS,." variants at the very first step? On my end, the file is nearly 20Gb in size and recoding the file (especially) if I have passed variants is a waste of space.

**Comment by chapmanb** [comment]
Thanks much for the question. For joint calling, I recommend using the GATK gVCF based approach rather than bcbio.variation.recall. This was written prior to having an open source gVCF based merging approach and is much less space and time efficient than GATK's approach. With GATK as a good viable option, this unfortunately hasn't got much work recently so suffers from some of the disk usage inefficiencies like you mention. Hope GATK will work for your needs.

**Comment by harish0201** [comment]
Hi,

Thank you for the comment!

I have tried both the local and spark based versions of GATK, but unfortunately, it seems to run forever (I have a big fat node :( ); whereas freebayes runs finished essentially overnight.

Anyways, thanks for the help and a happy week ahead!
